rate_dactra/teacher/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed, FileField
from wtforms import StringField, SubmitField, SelectField, BooleanField
from wtforms.fields.html5 import EmailField
from wtforms.validators import DataRequired, Length, Email, NoneOf

from rate_dactra import photos


class EditTeacherForm(FlaskForm):
    name = StringField('Teacher name', validators=[
        Length(max=42, min=2),
        NoneOf(['login', 'admin', 'compare'])
    ])
    photo = FileField('Teacher photo', validators=[
        FileAllowed(photos, 'Image only!')
    ])
    email = EmailField('Teacher email address', validators=[
        Email()
    ])
    phone = StringField('Teacher phone number', validators=[
        Length(min=10, max=13)
    ])
    submit = SubmitField('Edit')


class ReviewTeacherForm(FlaskForm):
    take_again = BooleanField('If you go back in time, would you take the class again?')
    attendance = BooleanField('Does the teacher care about attendance?')
    understanding = BooleanField('Do you understand from the teacher?')
    sexism = BooleanField('Does the teacher favour boys over girls or girls over boys? Sexist?')
    interesting = BooleanField('Is the teacher interesting?')
    english = BooleanField('Is the teacher good at English?')
    submit = SubmitField('Review')


class CommentOnTeacherForm(FlaskForm):
    course_name = StringField('Class name')
    grade_received = SelectField('Grade received',
                                 choices=(['A'] * 2,
                                          ['B'] * 2,
                                          ['C'] * 2,
                                          ['D'] * 2,
                                          ['F'] * 2),
                                 validators=[
                                     DataRequired()
                                 ])
    comment = StringField('Comment', validators=[
        DataRequired
    ])
    submit = SubmitField('Comment')

rate_dactra/teacher/__init__.py
from flask import Blueprint

teacher = Blueprint('teacher', __name__)

from .views import *
from .forms import *

rate_dactra/teacher/views.py
from flask import redirect, render_template, flash, url_for

from . import teacher, forms
from .. import models, photos


@teacher.route('/<string:name>', methods=['GET', 'POST'])
def teacher_page(name):
    teacher = models.Teacher.query.filter_by(name=name).first_or_404()
    comments = models.Comment.query.filter_by(teacher=teacher).all()
    edit_teacher_form = forms.EditTeacherForm()
    review_teacher_form = forms.ReviewTeacherForm()
    comment_on_teacher_form = forms.CommentOnTeacherForm()

    reviews_num = (len(teacher.reviews) if teacher.reviews else 1) / 100
    teacher.take_again = (len([r for r in teacher.reviews if r.take_again])) // reviews_num
    teacher.attendance = (len([r for r in teacher.reviews if r.attendance])) // reviews_num
    teacher.understanding = (len([r for r in teacher.reviews if r.understanding])) // reviews_num
    teacher.sexism = (len([r for r in teacher.reviews if r.sexism])) // reviews_num
    teacher.interesting = (len([r for r in teacher.reviews if r.interesting])) // reviews_num
    teacher.english = (len([r for r in teacher.reviews if r.english])) // reviews_num

    over_all = (
        teacher.take_again, 100 - teacher.attendance, teacher.understanding, 100 - teacher.sexism,
        teacher.interesting, teacher.english)
    teacher.overall = sum(over_all) // len(over_all)

    context = {
        'teacher': teacher,
        'comments': comments,
        'edit_teacher_form': edit_teacher_form,
        'review_teacher_form': review_teacher_form,
        'comment_on_teacher_form': comment_on_teacher_form
    }
    return render_template('teacher/teacher_page.html', **context)


@teacher.route('/edit/<string:name>', methods=['POST'])
def edit_teacher(name):
    teacher = models.Teacher.query.filter_by(name=name).first_or_404()
    edit_teacher_form = forms.EditTeacherForm()
    if edit_teacher_form.name.data:
        if edit_teacher_form.name.validate(edit_teacher_form):
            teacher.name = edit_teacher_form.name.data.lower()
            teacher.is_approved = False
            flash(f'Name changed to {teacher.name.title()}')
    if edit_teacher_form.photo.data:
        if edit_teacher_form.photo.validate(edit_teacher_form):
            filename = photos.save(edit_teacher_form.photo.data)
            teacher.photo = photos.url(filename)
            teacher.is_approved = False
            flash(f'Photo changed to .. You can see it down below!')
    if edit_teacher_form.email.data:
        if edit_teacher_form.email.validate(edit_teacher_form):
            teacher.email = edit_teacher_form.email.data
            teacher.is_approved = False
            flash(f'Email changed to {teacher.email}')
    if edit_teacher_form.phone.data:
        if edit_teacher_form.phone.validate(edit_teacher_form):
            teacher.phone = edit_teacher_form.phone.data
            teacher.is_approved = False
            flash(f'Phone changed to {teacher.phone}')

    models.db.session.add(teacher)
    models.db.session.commit()
    return redirect(url_for('.teacher_page', name=teacher.name))


@teacher.route('/review/<string:name>', methods=['POST'])
def review_teacher(name):
    teacher = models.Teacher.query.filter_by(name=name).first_or_404()
    review_teacher_form = forms.ReviewTeacherForm()
    review = models.Review(take_again=review_teacher_form.take_again.data,
                           attendance=review_teacher_form.attendance.data,
                           understanding=review_teacher_form.understanding.data,
                           sexism=review_teacher_form.sexism.data,
                           interesting=review_teacher_form.interesting.data,
                           english=review_teacher_form.english.data,
                           teacher=teacher)
    models.db.session.add(review)
    models.db.session.commit()
    flash('Thank you for your review! You are Cute! :D', 'info')
    return redirect(url_for('.teacher_page', name=name))


@teacher.route('/comment/<string:name>', methods=['POST'])
def comment_on_teacher(name):
    teacher = models.Teacher.query.filter_by(name=name).first_or_404()
    comment_on_teacher_form = forms.CommentOnTeacherForm()
    comment = models.Comment(course_name=comment_on_teacher_form.course_name.data,
                             grade_received=comment_on_teacher_form.grade_received.data,
                             comment=comment_on_teacher_form.comment.data,
                             teacher=teacher)
    models.db.session.add(comment)
    models.db.session.commit()
    flash('Than you for your comment! You are Cute! :D')
    return redirect(url_for('.teacher_page', name=name))

rate_dactra/templates/teacher/teacher_page.html
{% extends 'base.html' %}

{% block title %}{{ teacher.name|title }}{{ super() }}{% endblock %}

{% block page_content %}
    <div class="page-header">
        <p> You can edit the teacher's personal info here, review him/her or leave a comment on him/her.</p>
    </div>
    <div class="container">
        <div class="row">
            <div class="row">
                <div class='col m-1 w-100'>
                    <div class="card">
                        {% if teacher.photo %}
                            <img src="{{ teacher.photo }}" class="card-img-top">
                        {% endif %}
                        <div class="card-body">
                            <h1 class="card-title">{{ teacher.name|title }}</h1>
                            {% if teacher.email %}
                                <h4 class="card-text">Email: {{ teacher.email }}</h4>
                            {% endif %}
                            {% if teacher.phone %}
                                <h4 class="card-text">Phone: {{ teacher.phone }}</h4>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="col m-1 w-100">
                    <h2>Edit {{ teacher.name|title }}'s info</h2>
                    {#                    {{ wtf.quick_form(edit_teacher_form, action=url_for('teacher.edit_teacher', name=teacher.name)) }}#}
                </div>
                <div class="col m-1 w-100">
                    <h2>Review {{ teacher.name|title }}</h2>
                    <p>(check the box for yes and leave it blank for no)</p>
                    {#                    {{ wtf.quick_form(review_teacher_form, action=url_for('teacher.review_teacher', name=teacher.name)) }}#}
                </div>
                <div class="col m-1 w-100">
                    <h2>Comment on {{ teacher.name|title }}</h2>
                    {#                    {{ wtf.quick_form(comment_on_teacher_form, action=url_for('teacher.comment_on_teacher', name=teacher.name)) }}#}
                </div>
            </div>
            <div class="col">
                {% if teacher.reviews %}
                    <div class="card w-auto m-1">
                        <div class="card-header">Review</div>
                        <ul class="list-group list-group-flush">
                            {% if teacher.overall >= 50 %}
                                <li class="list-group-item text-white bg-success">Overall I
                                    give {{ teacher.name|title }}
                                    a {{ teacher.overall }}%. Not bad!
                                </li>
                            {% else %}
                                <li class="list-group-item text-white bg-danger">Overall I give {{ teacher.name|title }}
                                    a {{ teacher.overall }}%. Huh,
                                    is {{ teacher.name|title }} even trying!
                                </li>
                            {% endif %}
                            {% if teacher.take_again >= 50 %}
                                <li class="list-group-item text-white bg-success">{{ teacher.take_again }}% students
                                    would
                                    take {{ teacher.name|title }}'s class again. Nice,
                                    must
                                    have been a nice experience.
                                </li>
                            {% else %}
                                <li class="list-group-item text-white bg-danger">{{ teacher.take_again }}% students
                                    would
                                    take {{ teacher.name|title }}'s class again. Wow,
                                    just
                                    walk away buddy.
                                </li>
                            {% endif %}
                            {% if teacher.attendance >= 50 %}
                                <li class="list-group-item text-white bg-danger">{{ teacher.attendance }}% students
                                    think {{ teacher.name|title }} cares about attendance.
                                    Don't
                                    miss a lecture.
                                </li>
                            {% else %}
                                <li class="list-group-item text-white bg-success">{{ teacher.attendance }}% students
                                    think {{ teacher.name|title }} cares about attendance.
                                    Now
                                    you can sleep in like a baby I guess!
                                </li>
                            {% endif %}
                            {% if teacher.understanding >= 50 %}
                                <li class="list-group-item text-white bg-success">{{ teacher.understanding }}% students
                                    can
                                    understand from {{ teacher.name|title }}.
                                    Nnnnnnnice!
                                </li>
                            {% else %}
                                <li class="list-group-item text-white bg-danger">{{ teacher.understanding }}% students
                                    can
                                    understand from {{ teacher.name|title }}. The art
                                    of
                                    reading powerpoint slides
                                </li>
                            {% endif %}
                            {% if teacher.sexism >= 50 %}
                                <li class="list-group-item text-white bg-danger">{{ teacher.sexism }}% students
                                    find {{ teacher.name|title }} sexist. Shame on you wallahi!
                                </li>
                            {% else %}
                                <li class="list-group-item text-white bg-success">{{ teacher.sexism }}% students
                                    find {{ teacher.name|title }}
                                    sexist. {{ teacher.name|title }}
                                    you make me proud.
                                </li>
                            {% endif %}
                            {% if teacher.bedan >= 50 %}
                                <li class="list-group-item text-white bg-danger">{{ teacher.bedan }}% students
                                    think {{ teacher.name|title }} is bedan. :) ...
                                </li>
                            {% else %}
                                <li class="list-group-item text-white bg-success">{{ teacher.bedan }}% students
                                    think {{ teacher.name|title }} is bedan. So nice teachers do
                                    exists? Huh!
                                </li>
                            {% endif %}
                            {% if teacher.interesting >= 50 %}
                                <li class="list-group-item text-white bg-success">{{ teacher.interesting }}% students
                                    find {{ teacher.name|title }} interesting. Yayyyyy!
                                </li>
                            {% else %}
                                <li class="list-group-item text-white bg-danger">{{ teacher.interesting }}% students
                                    find {{ teacher.name|title }} interesting. Have some
                                    coffee
                                    before {{ teacher.name|title }}'s lecture.
                                </li>
                            {% endif %}
                            {% if teacher.english >= 50 %}
                                <li class="list-group-item text-white bg-success">{{ teacher.english }}% students
                                    think {{ teacher.name|title }} is good at English. Good for
                                    you {{ teacher.name|title }}.
                                </li>
                            {% else %}
                                <li class="list-group-item text-white bg-danger">{{ teacher.english }}% students
                                    think {{ teacher.name|title }} is good at English. If you
                                    are a
                                    foreigner, Take a translator with you!
                                </li>
                            {% endif %}
                        </ul>
                    </div>
                {% endif %}
            </div>
        </div>
        <div class="row-fluid">
            {% if comments %}
                <div class="card-deck">
                    {% for comment in comments %}
                        <div class="col-sm-3">
                            <div class="card w-auto m-1">
                                <div class="card-body">
                                    <h5 class="card-title">A student who got <b>{{ comment.grade_received }}</b> on
                                        <b>{{ comment.course_name }}</b> thinks:</h5>
                                    <p class="card-text">{{ comment.comment }}</p>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
    </div>

    </div>
{% endblock %}